### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dawnfire05** [dawnfire05/happit-flutter#3]
widget
- [ ] habit widget

ui
- [x] habit add screen
- [x] habit added screen
- [ ] login screen
- [ ] onboarding screen

business logic
- [ ] habit widget
- [ ] habit add screen
- [ ] habit added screen
- [ ] login screen
